### PR TITLE
Done NavBar as per figma desgin

### PR DESCRIPTION
**Pull request by mrshivamshaw**
### Related Issue
- Issue number goes here: #1 

### Proposed Changes 
- Change 1
- Change 2
- Change 3

### Checklist 
- [x] Documentation of the code 
- [x] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine

### Screenshots
 
Screenshot 2023-10-21 164900

### CODE REVIEW

**Comment by TheCodeVenturer** [comment]
Hey @shivamshaw07,
Will you delete this PR and resend a Fresh new PR
Updating this all

**Comment by paardarshee** [comment]
Hey @shivamshaw07,
Will you please delete this PR and send a new PR

**Review by paardarshee — APPROVED** [review]

**Comment by paardarshee** [comment]
@shivamshaw07 can you update now?

**Comment by mrshivamshaw** [comment]
Yes bhaiya

**Pull request closed without merging**
