### PR TITLE
Added navBar 

### PR DESCRIPTION
**Pull request by mrshivamshaw**
### Related Issue #1 
- Issue number goes here: #1

### Proposed Changes 
Added NavBar and also routers which will make the work easier for other contributers

### Checklist 
- [x] Documentation of the code 
- [x] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine

### CODE REVIEW

**Comment by mrshivamshaw** [comment]
Screenshot 2023-10-20 212612

**Comment by TheCodeVenturer** [comment]
@shivamshaw07, follow The Figma Design

**Review by paardarshee — CHANGES_REQUESTED** [review]
Hey @shivamshaw07, our website is SPA so 
- we do not need react-router now, if will need in the future will implement it, 
- Make only Navbar Component rest leave on others
- Follow the Figma Design Strictly.

**Comment by mrshivamshaw** [comment]
@TheCodeVenturer ok bhaiya

**Pull request closed without merging**
